# Opcional podría agregar esto: http://kanban.leanlabs.io/docs/installation/docker.html 
- name: instalar_gitlab_postgres
  docker:
    name: "gitlab-postgresql"
    image: "sameersbn/postgresql:9.4-12"
    state: reloaded
    volumes:
    - "/data/gitlab-postgresql:/var/lib/postgresql"
    env:
        DB_NAME: gitlabhq_production
        DB_USER: gitlab
        DB_PASS: "{{ redis_postgresql_db_password }}"
    restart_policy: always

- name: instalar_gitlab_redis
  docker:
    name: "gitlab-redis"
    image: "sameersbn/redis:latest"
    state: reloaded
    volumes:
    - "/data/gitlab-redis:/var/lib/redis"
    restart_policy: always

- name: instalar_gitlab
  docker:
    name: "gitlab"
    image: "sameersbn/gitlab:8.4.4"
    state: reloaded
    volumes:
    - "/data/gitlab-repos:/home/git/data"
    ports:
    - "22:22"
    - "8002:80"
    links:
    - "gitlab-postgresql:postgresql"
    - "gitlab-redis:redisio"
    env:
        GITLAB_PORT: 80
        GITLAB_HOST: gitlab.dev-tools.msgc.gcba
        GITLAB_SSH_PORT: 22
        GITLAB_SECRETS_DB_KEY_BASE: "{{ gitlab_secrets_db_key_base }}"
        SMTP_DOMAIN: "{{ smtp_domain }}"
        SMTP_HOST: "{{ smtp_host }}"
        SMTP_PORT: "{{ smtp_port }}"
        SMTP_USER: "{{ smtp_user }}"
        SMTP_PASS: "{{ smtp_pass }}"
        GITLAB_EMAIL: "{{ gitlab_email }}"
        GITLAB_EMAIL_REPLY_TO: "{{ gitlab_email_reply_to }}"
        VIRTUAL_HOST: gitlab.dev-tools.msgc.gcba
        VIRTUAL_PORT: 80
    restart_policy: always

