- name: aseguro_directorio_data_nginx_existe
  file: path=/data/nginx/etc state=directory

- name: copio_archivo_configuracion_phpmyadmin_1
  copy: src="files/client_max_body_size.conf" dest="/data/nginx/etc/client_max_body_size.conf"

- name: copio_configuracion_header
  copy: src="files/connection_header.conf" dest="/data/nginx/etc/connection_header.conf"

- name: instalar_nginx_proxy
  docker_container:
    name: nginx_proxy
    image: "jwilder/nginx-proxy"
    state: started
    restart: true
    restart_policy: always
    volumes:
        - "/var/run/docker.sock:/tmp/docker.sock:ro"
        - "/data/nginx/etc/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf"
        - "/data/nginx/etc/connection_header.conf:/etc/nginx/conf.d/connection_header.conf"
    ports:
    - "80:80"
