- name: Instalar mailcatcher
  docker_container:
    name: mailcatcher
    image: "tophfr/mailcatcher"
    state: started
    restart: true
    restart_policy: always
    env:
        VIRTUAL_HOST: "mailcatcher.dev-apps.msgc.gcba"
    ports:
    - "1080:80"
    - "1025:25"
