- name: Instalar mailcatcher
  docker_container:
    name: mailcatcher
    image: "tophfr/mailcatcher"
    state: started
    recreate: true
    restart_policy: always
    labels:
      traefik.docker.network: "mailcatcher_network"
      traefik.frontend.rule: "Host: mailcatcher.dev-capacitacion.msgc.gcba"
      traefik.enable: "true"
      traefik.port: "80"


- name: Crear red de mailcatcher
  docker_network:
    name: mailcatcher_network
    state: present
    connected:
      - mailcatcher
      - "reverse-proxy"
