- name: instalar_taiga_data
  docker:
    name: "data"
    image: "tianon/true"
    state: reloaded
    restart_policy: always
    volumes:
    - "/data/taiga_data/postgresql:/var/lib/postgresql/data"
    - "/data/taiga_data/media:/usr/local/taiga/media"
    - "/data/taiga_data/static:/usr/local/taiga/static"
    - "/data/taiga_data/logs:/usr/local/taiga/logs"

- name: instalar_taiga_db
  docker:
    name: "taigadb"
    image: "postgres"
    state: reloaded
    restart_policy: always
    volumes_from:
    - "data"
    env:
        POSTGRES_USER: "{{ taiga_postgres_user }}"
        POSTGRES_PASSWORD: "{{ taiga_postgres_password }}"

- name: instalar_taiga_back
  docker:
    name: "taigaback"
    image: "htdvisser/taiga-back:stable"
    hostname: "taiga.dev-tools.msgc.gcba"
    state: reloaded
    restart_policy: always
    links:
    - "taigadb:postgres"
    volumes_from:
    - "data"
    env:
        SECRET_KEY: Un1c0rns_4r3_4w3s0m3
        DEBUG: "False"
        EMAIL_USE_TLS: "True"
        SMTP_DOMAIN: "{{ smtp_domain }}"
        EMAIL_HOST: "{{ smtp_host }}"
        EMAIL_PORT: "{{ smtp_port }}"
        EMAIL_HOST_USER: "{{ smtp_user }}"
        EMAIL_HOST_PASSWORD: "{{ smtp_pass }}"
        DEFAULT_FROM_EMAIL: "{{ default_email_reply_to }}"

- name: instalar_taiga_front
  docker:
    name: "taigafront"
    image: "htdvisser/taiga-front-dist:stable"
    hostname: "taiga.dev-tools.msgc.gcba"
    links:
    - "taigaback"
    volumes_from:
    - "data"
    restart_policy: always
    ports:
    - "80"
    env:
        DEFAULT_LANGUAGE: es
        VIRTUAL_HOST: taiga.dev-tools.msgc.gcba
