- name: Creo network para que taiga pueda enviar mails
  docker_network:
    name: taigalgc
    state: present
    # ipam_options:
    #   subnet: 10.47.4.0/22
    connected:
      - reverse-proxy
    force: yes

- name: instalar_taiga_db
  docker_container:
    name: taigadblgc
    image: postgres:9.5
    state: started
    networks:
      - name: taigalgc
    restart_policy: always
    volumes:
      - "{{ taigalgc_data_path }}/postgresql:/var/lib/postgresql/data"
    env:
        POSTGRES_USER: "{{ taiga_postgres_user }}"
        POSTGRES_PASSWORD: "{{ taiga_postgres_password }}"

- name: instalar_taiga_back
  docker_container:
    name: taigabacklgc
    image: bartoszgadzala/taiga-back:3.1.0
    hostname: "{{ taigalgc_hostname }}"
    state: started
    networks:
      - name: taigalgc
        # ipv4_address: 10.47.4.114
    restart_policy: always
    links:
      - taigadblgc:postgres
    volumes:
      - "{{ taigalgc_data_path }}/media:/usr/local/taiga/media"
      - "{{ taigalgc_data_path }}/static:/usr/local/taiga/static"
      - "{{ taigalgc_data_path }}/logs:/usr/local/taiga/logs"
    env:
      HOSTNAME: "{{ taigalgc_hostname }}"
      SECRET_KEY: Un1c0rns_4r3_4w3s0m3
      DEBUG: "False"
      EMAIL_USE_TLS: "True"
      SMTP_DOMAIN: "{{ smtp_domain }}"
      EMAIL_HOST: "{{ smtp_host }}"
      EMAIL_PORT: "{{ smtp_port }}"
      EMAIL_HOST_USER: "{{ smtp_user }}"
      EMAIL_HOST_PASSWORD: "{{ smtp_pass }}"
      DEFAULT_FROM_EMAIL: "{{ default_email_reply_to }}"
      POSTGRES_DB_NAME: taiga
      POSTGRES_HOST: taigadblgc
      POSTGRES_PORT: 5432
      POSTGRES_USER: "{{ taiga_postgres_user }}"
      POSTGRES_PASSWORD: "{{ taiga_postgres_password }}"

- name: instalar_taiga_front
  docker_container:
    name: taigafrontlgc
    image: bartoszgadzala/taiga-front:3.1.0
    state: started
    hostname: "{{ taigalgc_hostname }}"
    networks:
      - name: taigalgc
        # ipv4_address: 10.47.4.115
    links:
      - taigabacklgc
    volumes:
      - "{{ taigalgc_data_path }}/media:/usr/local/taiga/media"
      - "{{ taigalgc_data_path }}/static:/usr/local/taiga/static"
    restart_policy: always
    ports:
    - "{{ taigalgc_front_port }}80"
    env:
        DEFAULT_LANGUAGE: es
        VIRTUAL_HOST: "{{ taigalgc_hostname }}"
        TAIGABACK_PORT_8000_TCP_ADDR: taigabacklgc
