################################################################
# Global configuration
################################################################
debug = false
logLevel = "DEBUG"

################################################################
# Entrypoints configuration
################################################################
[entryPoints]
  [entryPoints.http]
  address = ":80"

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
[api]
dashboard = true

################################################################
# Ping configuration
################################################################

# Enable ping
[ping]

################################################################
# Docker configuration backend
################################################################
[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false
